# Generated by Django 2.2.4 on 2019-09-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=64)),
                ('genre', models.CharField(max_length=64)),
                ('rating', models.FloatField()),
                ('author', models.CharField(max_length=64)),
            ],
        ),
    ]
